#!/bin/bash

# ==================================================================================================
# ============================# Synchronous Multisplitting=====================================
# ==================================================================================================



petscmpiexec -n 2 ./bin/synchronous-multisplitting -npb 1  -m 128 -n 128  -rtol 1e-3 -inner_ksp_type gmres -inner_ksp_rtol 1e-3 -inner_ksp_max_it 40 -inner_pc_type none -options_view -options_left  

# ==================================================================================================
# ============================# # Asynchronous Multisplitting=======================================
# ==================================================================================================



petscmpiexec -n 2 ./bin/asynchronous-multisplitting  -npb 1 -m 128 -n 128 -min_convergence_count 4  -rtol 1e-3 -inner_ksp_type gmres -inner_ksp_rtol 1e-3 -inner_ksp_max_it 40 -inner_pc_type none -options_view -options_left     

# ==================================================================================================
# =========================# Synchronous Multisplitting & Synchronous LOCAL minimization============
# ==================================================================================================



petscmpiexec -n 2 ./bin/synchronous-multisplitting-synchronous-minimization-local -npb 1 -m 128 -n 128   -s 4   -rtol 1e-3 -inner_ksp_type gmres -inner_ksp_rtol 1e-3 -inner_ksp_max_it 20 -inner_pc_type none -outer_ksp_type cg -outer_ksp_rtol 1e-20 -outer_ksp_max_it 100000 -outer_pc_type none -options_view -options_left     


# ==================================================================================================
# ==================# # Asynchronous Multisplitting & Asynchronous LOCAL minimization===============
# ==================================================================================================



petscmpiexec -n 2 ./bin/asynchronous-multisplitting-asynchronous-minimization-local  -npb 1 -m 128 -n 128  -s 4 -min_convergence_count 4 -rtol 1e-3  -inner_ksp_type gmres -inner_ksp_rtol 1e-3 -inner_ksp_max_it 40 -inner_pc_type none -outer_ksp_type cg -outer_ksp_rtol 1e-10 -outer_ksp_max_it 100000 -outer_pc_type none -options_view -options_left  -inner_ksp_min_it 2 

# ==================================================================================================
# ===========# # Synchronous Multisplitting & Synchronous GLOBAL minimization=======================
# ==================================================================================================




petscmpiexec -n 2 ./bin/synchronous-multisplitting-synchronous-minimization-global -npb 1  -m 128 -n 128   -s 4  -rtol 1e-3 -inner_ksp_type gmres -inner_ksp_rtol 1e-3 -inner_ksp_max_it 40 -inner_pc_type none -outer_ksp_type cg -outer_ksp_rtol 1e-20 -outer_ksp_max_it 100000 -outer_pc_type none -options_view -options_left    

# ==================================================================================================
# ========= # Asynchronous Multisplitting & Asynchronous GLOBAL minimization========================
# ==================================================================================================


petscmpiexec -n 2 ./bin/asynchronous-multisplitting-asynchronous-minimization-global  -npb 1 -m 128 -n 128  -s 4 -min_convergence_count 4 -rtol 1e-3 -inner_ksp_type gmres -inner_ksp_rtol 1e-3 -inner_ksp_max_it 40 -inner_pc_type none -outer_ksp_type cg -outer_ksp_rtol 1e-10 -outer_ksp_max_it 100000 -outer_pc_type none -options_view -options_left    


# ==================================================================================================
# ==================================================================================================
# ==================================================================================================