#!/bin/bash

# Set the duration for the timeout
TIMEOUT_DURATION="600"

# Additionnal grace period
ADDITIONAL_GRACE_PERIOD="5s"

# mkdir -p ./tmp/logs
# mkdir -p ./tmp/logs_SM
# mkdir -p ./tmp/logs_AM
# mkdir -p ./tmp/logs_SMSM_LOCAL
# mkdir -p ./tmp/logs_AMAM_LOCAL
# mkdir -p ./tmp/logs_SMSM_GLOBAL
# mkdir -p ./tmp/logs_AMAM_GLOBAL
# rm -drf ./tmp/logs_SM/*
# rm -drf ./tmp/logs_AM/*
# rm -drf ./tmp/logs_SMSM_LOCAL/*
# rm -drf ./tmp/logs_AMAM_LOCAL/*
# rm -drf ./tmp/logs_SMSM_GLOBAL/*
# rm -drf ./tmp/logs_AMAM_GLOBAL/*

set -x  # Enable command tracing






# ==================================================================================================
# ============================# GMRES SOLUTION =====================================
# ==================================================================================================


# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/gmres_solution-v1.0 \
# -m 32 -n 32  \
# -ksp_type gmres -ksp_rtol 1e-3 -ksp_atol 1e-100 -ksp_max_it 1000000000 -pc_type  none \
# -ksp_norm_type UNPRECONDITIONED -ksp_converged_use_initial_residual_norm \
# -ksp_gmres_restart 30 \
# -ksp_converged_reason -ksp_view_final_residual  -ksp_error_if_not_converged -ksp_view_pre  \
# -options_view -options_left -log_view 




# ==================================================================================================
# ============================# Synchronous Multisplitting=====================================
# ==================================================================================================

# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-v1.0  -npb 1  \
# -m 512 -n 512  -rtol 1.e-5  \
# -inner1_ksp_type gmres -inner1_ksp_atol 1e-100  -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 50 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED -inner1_ksp_converged_use_initial_residual_norm       -inner1_ksp_monitor_true_residual ascii:./tmp/SM/saved_tmp/inner1_ksp.jl  \
# -inner2_ksp_type gmres -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 50 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED -inner2_ksp_converged_use_initial_residual_norm      -inner2_ksp_monitor_true_residual ascii:./tmp/SM/saved_tmp/inner2_ksp.jl  \
# -options_view -options_left  -log_view  > ./tmp/SM/saved_tmp/output.jl 2>&1


# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-v1.0  -npb 1  \
# -m 512 -n 512  -rtol 4.e-6  \
# -inner1_ksp_type gmres -inner1_ksp_atol 1e-100  -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 30 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED -inner1_ksp_converged_use_initial_residual_norm       \
# -inner2_ksp_type gmres -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 30 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED -inner2_ksp_converged_use_initial_residual_norm     \
# -options_view -options_left  -log_view  > ./tmp/SM/saved_tmp/output_clean.jl 2>&1


# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-v1.0  -npb 1 \
# -m 512 -n 512  -rtol 1e-8  \
# -inner1_ksp_type gmres -inner1_ksp_atol 1e-100  -inner1_ksp_rtol 1e-3 -inner1_ksp_max_it 50 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED -inner1_ksp_converged_use_initial_residual_norm     \
# -inner2_ksp_type gmres -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-3 -inner2_ksp_max_it 50 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED -inner2_ksp_converged_use_initial_residual_norm    \
# -options_view -options_left  -log_view  > ./tmp/SM/log_4_0.jl 2>&1


# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-v1.0  -npb 1 \
# -m 512 -n 512  -rtol 1e-6  \
# -inner1_ksp_type gmres -inner1_ksp_atol 1e-100  -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 50 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED -inner1_ksp_converged_use_initial_residual_norm     \
# -inner2_ksp_type gmres -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 50 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED -inner2_ksp_converged_use_initial_residual_norm    \
# -options_view -options_left  -log_view  > ./tmp/SM/log_3_0_temp2.jl 2>&1

# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-v1.0  -npb 1 \
# -m 512 -n 512  -rtol 1e-6  \
# -inner1_ksp_type gmres -inner1_ksp_atol 1e-100  -inner1_ksp_rtol 1e-6 -inner1_ksp_max_it 50 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED -inner1_ksp_converged_use_initial_residual_norm     \
# -inner2_ksp_type gmres -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-6 -inner2_ksp_max_it 50 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED -inner2_ksp_converged_use_initial_residual_norm    \
# -options_view -options_left  -log_view  > ./tmp/SM/log_3_0_temp3.jl 2>&1






# ==================================================================================================
# ============================# # Asynchronous Multisplitting=======================================
# ==================================================================================================






# ==================================================================================================
# =========================# Synchronous Multisplitting & Synchronous LOCAL minimization============
# ==================================================================================================
# -m 512 -n 512  -s 10 -rtol 7.e-7  


# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-synchronous-minimization-local-v1.0  -npb 1 \
# -m 512 -n 512  -s 4 -rtol 1e-6  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-6 -inner1_ksp_max_it 30 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED  \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-6 -inner2_ksp_max_it 30 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED   \
# -outer1_ksp_type lsqr -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-12 -outer1_ksp_max_it 1000 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED     \
# -outer2_ksp_type lsqr -outer2_ksp_lsqr_exact_mat_norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-12 -outer2_ksp_max_it 1000 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED   \
# -options_view -options_left -log_view  > ./tmp/SMSM_LOCAL/tmp_3_1.yml 2>&1 



# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-synchronous-minimization-local-v1.0  -npb 1 \
# -m 512 -n 512  -s 10 -rtol 7.e-7  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 20 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED  -inner1_ksp_monitor_true_residual ascii:./tmp/SMSM_LOCAL/saved_tmp/inner1_ksp.yml \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 20 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED  -inner2_ksp_monitor_true_residual ascii:./tmp/SMSM_LOCAL/saved_tmp/inner2_ksp.yml \
# -outer1_ksp_type lsqr -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-20 -outer1_ksp_max_it 30 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED    -outer1_ksp_monitor_true_residual ascii:./tmp/SMSM_LOCAL/saved_tmp/outer1_ksp.yml -outer1_ksp_lsqr_monitor ascii:./tmp/SMSM_LOCAL/saved_tmp/outer1_lsqr.yml  \
# -outer2_ksp_type lsqr -outer2_ksp_lsqr_exact_mat_norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-20 -outer2_ksp_max_it 30 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED     -outer2_ksp_monitor_true_residual ascii:./tmp/SMSM_LOCAL/saved_tmp/outer2_ksp.yml -outer2_ksp_lsqr_monitor ascii:./tmp/SMSM_LOCAL/saved_tmp/outer2_lsqr.yml  \
# -options_view -options_left -log_view  > ./tmp/SMSM_LOCAL/saved_tmp/output.yml 2>&1 


# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-synchronous-minimization-local-v1.0  -npb 1 \
# -m 512 -n 512  -s 2 -rtol 7.e-7  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 20 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED   \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 20 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED   \
# -outer1_ksp_type lsqr -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-50 -outer1_ksp_max_it 50 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED       \
# -outer2_ksp_type lsqr -outer2_ksp_lsqr_exact_mat_norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-50 -outer2_ksp_max_it 50 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED     \
# -options_view -options_left -log_view  > ./tmp/SMSM_LOCAL/saved_tmp/output.yml 2>&1 


# ==================================================================================================
# ==================# # Asynchronous Multisplitting & Asynchronous LOCAL minimization===============
# ==================================================================================================






# ==================================================================================================
# ===========# # Synchronous Multisplitting & Synchronous GLOBAL minimization=======================
# ==================================================================================================


# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 4 ./bin/synchronous-multisplitting-synchronous-minimization-global-v1.0  -npb 2 \
# -m 32 -n 32  -s 10 -rtol 1e-6  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-3 -inner1_ksp_max_it 20 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED   \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-3 -inner2_ksp_max_it 20 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED   \
# -outer1_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-20 -outer1_ksp_max_it 70 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED       \
# -outer2_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-20 -outer2_ksp_max_it 70 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED       \
# -options_view -options_left -log_view 




# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-synchronous-minimization-global-v1.0  -npb 1 \
# -m 512 -n 512  -s 10 -rtol 1e-6  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-3 -inner1_ksp_max_it 20 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED  -inner1_ksp_monitor_true_residual ascii:./tmp/test_procs/procs_2/inner1_ksp.yml \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-3 -inner2_ksp_max_it 20 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED  -inner2_ksp_monitor_true_residual ascii:./tmp/test_procs/procs_2/inner2_ksp.yml \
# -outer1_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-20 -outer1_ksp_max_it 70 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED    -outer1_ksp_converged_reason -outer1_ksp_monitor_true_residual ascii:./tmp/test_procs/procs_2/outer1_ksp.yml -outer1_ksp_lsqr_monitor ascii:./tmp/test_procs/procs_2/outer1_lsqr.yml   \
# -outer2_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_ norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-20 -outer2_ksp_max_it 70 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED    -outer2_ksp_converged_reason -outer2_ksp_monitor_true_residual ascii:./tmp/test_procs/procs_2/outer2_ksp.yml  -outer2_ksp_lsqr_monitor ascii:./tmp/test_procs/procs_2/outer2_lsqr.yml  \
# -options_view -options_left -log_view  > ./tmp/test_procs/procs_2/output.yml 2>&1 



# ==================================================================================================
# ========= # Asynchronous Multisplitting & Asynchronous GLOBAL minimization========================
# ==================================================================================================








# ==================================================================================================
# =========================# Synchronous Multisplitting & Synchronous SEMI LOCAL minimization ============
# ==================================================================================================


# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-synchronous-minimization-semi-local-v1.0  -npb 1 \
# -m 512 -n 512  -s 5 -rtol 9.e-6  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 20 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED  \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 20 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED   \
# -outer1_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-50 -outer1_ksp_max_it 100 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED       \
# -outer2_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_ norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-50 -outer2_ksp_max_it 100 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED       \
# -options_view -options_left -log_view > ./tmp/SMSM_SEMI_LOCAL/saved_tmp/output.yml 2>&1 


# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-synchronous-minimization-semi-local-v1.0  -npb 1 \
# -m 512 -n 512  -s 5 -rtol 9.e-6  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 20 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED  -inner1_ksp_monitor_true_residual ascii:./tmp/SMSM_SEMI_LOCAL/saved_tmp/inner1_ksp.yml \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 20 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED  -inner2_ksp_monitor_true_residual ascii:./tmp/SMSM_SEMI_LOCAL/saved_tmp/inner2_ksp.yml \
# -outer1_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-50 -outer1_ksp_max_it 100 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED    -outer1_ksp_converged_reason -outer1_ksp_monitor_true_residual ascii:./tmp/SMSM_SEMI_LOCAL/saved_tmp/outer1_ksp.yml -outer1_ksp_lsqr_monitor ascii:./tmp/SMSM_SEMI_LOCAL/saved_tmp/outer1_lsqr.yml   \
# -outer2_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_ norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-50 -outer2_ksp_max_it 100 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED    -outer2_ksp_converged_reason -outer2_ksp_monitor_true_residual ascii:./tmp/SMSM_SEMI_LOCAL/saved_tmp/outer2_ksp.yml  -outer2_ksp_lsqr_monitor ascii:./tmp/SMSM_SEMI_LOCAL/saved_tmp/outer2_lsqr.yml  \
# -options_view -options_left -log_view > ./tmp/SMSM_SEMI_LOCAL/saved_tmp/output.yml 2>&1 



# ==================================================================================================
# ==================================================================================================
# ==================================================================================================
set +x  # Disable command tracing

