#!/bin/bash

# Set the duration for the timeout
TIMEOUT_DURATION="5400"

# Additionnal grace period
ADDITIONAL_GRACE_PERIOD="5s"

# mkdir -p ./tmp/logs
# mkdir -p ./tmp/logs_SM
# mkdir -p ./tmp/logs_AM
# mkdir -p ./tmp/logs_SMSM_LOCAL
# mkdir -p ./tmp/logs_AMAM_LOCAL
# mkdir -p ./tmp/logs_SMSM_GLOBAL
# mkdir -p ./tmp/logs_AMAM_GLOBAL
# rm -drf ./tmp/logs_SM/*
# rm -drf ./tmp/logs_AM/*
# rm -drf ./tmp/logs_SMSM_LOCAL/*
# rm -drf ./tmp/logs_AMAM_LOCAL/*
# rm -drf ./tmp/logs_SMSM_GLOBAL/*
# rm -drf ./tmp/logs_AMAM_GLOBAL/*

set -x  # Enable command tracing






# ==================================================================================================
# ============================# XXX GMRES SOLUTION =====================================
# ==================================================================================================

# array_i=(nprocs mesh_size rtol)





# array_0=(16 2048 1.e-6)

# array_1=(16 1024 1.e-4)
# array_2=(16 2048 1.e-4)
# array_3=(16 4096 1.e-4)
# array_4=(16 8192 1.e-4)

# array_5=(32 1024 1.e-4)
# array_6=(32 2048 1.e-4)
# array_7=(32 4096 1.e-4)
# array_8=(32 8192 1.e-4)


# array_0=(16 8192 1.e-4)

# n=0

# for ((i=0; i<=n; i++)); do
#     varname="array_$i"
#     eval "vals=(\"\${${varname}[@]}\")"

#     mkdir -p "./tmp/GMRES/mesh_${vals[1]}_rennes"

#     timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
#     petscmpiexec -n ${vals[0]} ./bin/gmres_solution-v1.0 \
#     -m ${vals[1]} -n ${vals[1]}  \
#     -ksp_type gmres -ksp_rtol ${vals[2]} -ksp_atol 1e-100 -ksp_max_it 1000000000 -pc_type  none \
#     -ksp_norm_type UNPRECONDITIONED -ksp_converged_use_initial_residual_norm \
#     -ksp_gmres_restart 30 \
#     -ksp_converged_reason -ksp_view_final_residual  \
#     -log_view  > ./tmp/GMRES/mesh_${vals[1]}_rennes/mesh_${vals[1]}_${vals[0]}procs_${i}.jl 2>&1
# done



#     timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
#     petscmpiexec -n 16 ./bin/gmres_solution-v1.0 \
#     -m ${mesh_size[$i]} -n ${mesh_size[$i]}  \
#     -ksp_type gmres -ksp_rtol 1e-4 -ksp_atol 1e-100 -ksp_max_it 1000000000 -pc_type  none \
#     -ksp_norm_type UNPRECONDITIONED -ksp_converged_use_initial_residual_norm \
#     -ksp_gmres_restart 30 \
#     -ksp_converged_reason -ksp_view_final_residual  \
#     -log_view  > ./tmp/GMRES/mesh_${mesh_size[$i]}_grenoble/mesh_${mesh_size[$i]}_16procs.jl 2>&1


# ==================================================================================================
# ============================# XXX Synchronous Multisplitting=====================================
# ==================================================================================================

# -m 512 -n 512  -rtol 4.e-6  \

# array_i=(nprocs mesh_size rtol inner_max_it inner_rtol  )

array_0=(2 32 1.e-4  30 1.e-20)

array_1=(16 1024 1.e-4  20 1.e-20)
array_2=(16 1024 1.e-4  30 1.e-20)
array_3=(16 1024 1.e-4  40 1.e-20)
array_4=(16 1024 1.e-4  50 1.e-20)
array_5=(16 1024 1.e-4  60 1.e-20)
array_6=(16 1024 1.e-4  80 1.e-20)

array_7=(16 2048 1.e-4  20 1.e-20)
array_8=(16 2048 1.e-4  30 1.e-20)
array_9=(16 2048 1.e-4  40 1.e-20)
array_10=(16 2048 1.e-4  50 1.e-20)
array_11=(16 2048 1.e-4  60 1.e-20)
array_12=(16 2048 1.e-4  80 1.e-20)

array_13=(16 4096 1.e-4  20 1.e-20)
array_14=(16 4096 1.e-4  30 1.e-20)
array_15=(16 4096 1.e-4  40 1.e-20)
array_16=(16 4096 1.e-4  50 1.e-20)
array_17=(16 4096 1.e-4  60 1.e-20)
array_18=(16 4096 1.e-4  80 1.e-20)



n=18

for ((i=0; i<=n; i++)); do
    varname="array_$i"
    eval "vals=(\"\${${varname}[@]}\")"
    
    mkdir -p "./tmp/SM/mesh_${vals[1]}_rennes"

    timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
    petscmpiexec -n ${vals[0]} ./bin/synchronous-multisplitting-v1.0  -npb $(( ${vals[0]} / 2 ))  \
    -m ${vals[1]} -n ${vals[1]}  \
    -rtol ${vals[2]}  \
    -inner1_ksp_type gmres -inner1_ksp_atol 1e-100 -inner1_ksp_max_it ${vals[3]} -inner1_ksp_rtol ${vals[4]} -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED -inner1_ksp_converged_use_initial_residual_norm       \
    -inner2_ksp_type gmres -inner2_ksp_atol 1e-100 -inner2_ksp_max_it ${vals[3]} -inner2_ksp_rtol ${vals[4]}  -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED -inner2_ksp_converged_use_initial_residual_norm     \
    -options_view -options_left  -log_view  > ./tmp/SM/mesh_${vals[1]}_rennes/mesh_${vals[1]}_${vals[0]}procs_${i}.jl 2>&1

done


# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-v1.0  -npb 1  \
# -m 512 -n 512  -rtol 1.e-5  \
# -inner1_ksp_type gmres -inner1_ksp_atol 1e-100  -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 50 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED -inner1_ksp_converged_use_initial_residual_norm       -inner1_ksp_monitor_true_residual ascii:./tmp/SM/saved_tmp/inner1_ksp.jl  \
# -inner2_ksp_type gmres -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 50 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED -inner2_ksp_converged_use_initial_residual_norm      -inner2_ksp_monitor_true_residual ascii:./tmp/SM/saved_tmp/inner2_ksp.jl  \
# -options_view -options_left  -log_view  > ./tmp/SM/saved_tmp/output.jl 2>&1


# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-v1.0  -npb 1  \
# -m 512 -n 512  -rtol 4.e-6  \
# -inner1_ksp_type gmres -inner1_ksp_atol 1e-100  -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 30 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED -inner1_ksp_converged_use_initial_residual_norm       \
# -inner2_ksp_type gmres -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 30 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED -inner2_ksp_converged_use_initial_residual_norm     \
# -options_view -options_left  -log_view  > ./tmp/SM/saved_tmp/output_clean.jl 2>&1


# ==================================================================================================
# ============================# # XXX Asynchronous Multisplitting=======================================
# ==================================================================================================

# array_i=(nprocs mesh_size rtol inner_max_it inner_rtol  )


array_0=(2 32 4.e-6 4 30 1.e-20)

array_1=(16 1024 4.e-6 4  20 1.e-20)
array_2=(16 1024 4.e-6 4  30 1.e-20)
array_3=(16 1024 4.e-6 4  40 1.e-20)
array_4=(16 1024 4.e-6 4  50 1.e-20)
array_5=(16 1024 4.e-6 4  60 1.e-20)
array_6=(16 1024 4.e-6 4  80 1.e-20)

array_7=(16 2048 4.e-6 4  20 1.e-20)
array_8=(16 2048 4.e-6 4  30 1.e-20)
array_9=(16 2048 4.e-6 4  40 1.e-20)
array_10=(16 2048 4.e-6 4  50 1.e-20)
array_11=(16 2048 4.e-6 4  60 1.e-20)
array_12=(16 2048 4.e-6 4  80 1.e-20)

array_13=(16 4096 4.e-6 4  20 1.e-20)
array_14=(16 4096 4.e-6 4  30 1.e-20)
array_15=(16 4096 4.e-6 4  40 1.e-20)
array_16=(16 4096 4.e-6 4  50 1.e-20)
array_17=(16 4096 4.e-6 4  60 1.e-20)
array_18=(16 4096 4.e-6 4  80 1.e-20)

n=18

for ((i=0; i<=n; i++)); do
    varname="array_$i"
    eval "vals=(\"\${${varname}[@]}\")"

    mkdir -p "./tmp/AM/mesh_${vals[1]}_rennes"    

    timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
    petscmpiexec -n ${vals[0]} ./bin/asynchronous-multisplitting-v1.0  -npb $(( ${vals[0]} / 2 ))  \
    -m ${vals[1]} -n ${vals[1]}  \
    -rtol ${vals[2]}  \
    -min_convergence_count ${vals[3]} \
    -inner1_ksp_type gmres -inner1_ksp_atol 1e-100 -inner1_ksp_max_it ${vals[4]} -inner1_ksp_rtol ${vals[5]} -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED -inner1_ksp_converged_use_initial_residual_norm       \
    -inner2_ksp_type gmres -inner2_ksp_atol 1e-100 -inner2_ksp_max_it ${vals[4]} -inner2_ksp_rtol ${vals[5]}  -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED -inner2_ksp_converged_use_initial_residual_norm     \
    -options_view -options_left  -log_view  > ./tmp/AM/mesh_${vals[1]}_rennes/mesh_${vals[1]}_${vals[0]}procs_${i}.jl 2>&1

done


# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/asynchronous-multisplitting-v1.0  -npb 1  \
# -m 512 -n 512  -rtol 1.e-5  \
# -inner1_ksp_type gmres -inner1_ksp_atol 1e-100  -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 50 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED -inner1_ksp_converged_use_initial_residual_norm       -inner1_ksp_monitor_true_residual ascii:./tmp/SM/saved_tmp/inner1_ksp.jl  \
# -inner2_ksp_type gmres -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 50 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED -inner2_ksp_converged_use_initial_residual_norm      -inner2_ksp_monitor_true_residual ascii:./tmp/SM/saved_tmp/inner2_ksp.jl  \
# -options_view -options_left  -log_view  > ./tmp/SM/saved_tmp/output.jl 2>&1


# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/asynchronous-multisplitting-v1.0  -npb 1  \
# -m 512 -n 512  -rtol 4.e-6  \
# -inner1_ksp_type gmres -inner1_ksp_atol 1e-100  -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 30 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED -inner1_ksp_converged_use_initial_residual_norm       \
# -inner2_ksp_type gmres -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 30 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED -inner2_ksp_converged_use_initial_residual_norm     \
# -options_view -options_left  -log_view  > ./tmp/SM/saved_tmp/output_clean.jl 2>&1





# ==================================================================================================
# ===========# # XXX Synchronous Multisplitting & Synchronous GLOBAL minimization=======================
# ==================================================================================================



# array_i=(nprocs mesh_size rtol base_size inner_max_it inner_rtol outer_max_it outer_rtol )

# array_0=(16 2048 1.e-4  20  20 1.e-10 70 1.e-15)
# array_1=(16 4096 1.e-4  14  20 1.e-10 70 1.e-15)
# array_2=(16 8192 1.e-4  10  30 1.e-10 70 1.e-15)



# n=2


# for ((i=0; i<=n; i++)); do
#     varname="array_$i"
#     eval "vals=(\"\${${varname}[@]}\")"

#     mkdir -p "./tmp/SMSM_GLOBAL_tc/mesh_${vals[1]}_rennes"

#     timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
#     petscmpiexec -n ${vals[0]} ./bin/synchronous-multisplitting-synchronous-minimization-global-v1.0  -npb $(( ${vals[0]} / 2 )) \
#     -m ${vals[1]} -n ${vals[1]} \
#      -rtol ${vals[2]}  \
#      -s ${vals[3]} \
#     -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_max_it ${vals[4]} -inner1_ksp_rtol ${vals[5]}  -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED   \
#     -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_max_it ${vals[4]} -inner2_ksp_rtol ${vals[5]}  -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED   \
#     -outer1_ksp_type lsqr -outer1_ksp_convergence_test default  -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_max_it ${vals[6]} -outer1_ksp_rtol ${vals[7]}  -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED       \
#     -outer2_ksp_type lsqr -outer2_ksp_convergence_test default  -outer1_ksp_lsqr_exact_mat_norm -outer2_ksp_atol 1e-100 -outer2_ksp_max_it ${vals[6]} -outer2_ksp_rtol ${vals[7]}  -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED       \
#     -options_view -options_left -log_view   > ./tmp/SMSM_GLOBAL_tc/mesh_${vals[1]}_rennes/mesh_${vals[1]}_${vals[0]}procs_${i}.jl 2>&1 

# done








# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 16 ./bin/synchronous-multisplitting-synchronous-minimization-global-v1.0  -npb 8 \
# -m 4096 -n 4096  -s 15 -rtol 1e-4  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-3 -inner1_ksp_max_it 20 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED   \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-3 -inner2_ksp_max_it 20 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED   \
# -outer1_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-10 -outer1_ksp_max_it 60 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED       \
# -outer2_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-10 -outer2_ksp_max_it 60 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED       \
# -options_view -options_left -log_view   > ./tmp/SMSM_GLOBAL/mesh_4096_grenoble/mesh_4096_16procs_1_4.jl 2>&1 


# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 16 ./bin/synchronous-multisplitting-synchronous-minimization-global-v1.0  -npb 8 \
# -m 2048 -n 2048  -s 10 -rtol 1e-4  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-3 -inner1_ksp_max_it 40 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED  -inner1_ksp_monitor_true_residual ascii:./tmp/SMSM_GLOBAL/mesh_2048_grenoble/perfs/inner1_ksp.yml \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-3 -inner2_ksp_max_it 40 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED  -inner2_ksp_monitor_true_residual ascii:./tmp/SMSM_GLOBAL/mesh_2048_grenoble/perfs/inner2_ksp.yml \
# -outer1_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-14 -outer1_ksp_max_it 120 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED    -outer1_ksp_converged_reason -outer1_ksp_monitor_true_residual ascii:./tmp/SMSM_GLOBAL/mesh_2048_grenoble/perfs/outer1_ksp.yml -outer1_ksp_lsqr_monitor ascii:./tmp/SMSM_GLOBAL/mesh_2048_grenoble/perfs/outer1_lsqr.yml   \
# -outer2_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-14 -outer2_ksp_max_it 120 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED    -outer2_ksp_converged_reason -outer2_ksp_monitor_true_residual ascii:./tmp/SMSM_GLOBAL/mesh_2048_grenoble/perfs/outer2_ksp.yml  -outer2_ksp_lsqr_monitor ascii:./tmp/SMSM_GLOBAL/mesh_2048_grenoble/perfs/outer2_lsqr.yml  \
# -options_view -options_left -log_view   > ./tmp/SMSM_GLOBAL/mesh_2048_grenoble/perfs/mesh_2048_16procs.jl 2>&1 








# ==================================================================================================
# ========= # XXX Asynchronous Multisplitting & Asynchronous GLOBAL minimization========================
# ==================================================================================================




# array_i=(nprocs mesh_size rtol base_size min_conv_count inner_max_it inner_rtol outer_max_it outer_rtol )


array_0=(16 32 1.e-10  10  2 20 1.e-20 70 1.e-20)

array_1=(16 2048 1.e-4  20  2 20 1.e-10 70 1.e-15)
array_2=(16 4096 1.e-4  14  2 20 1.e-10 70 1.e-15)
array_3=(16 8192 1.e-4  10  2 30 1.e-10 70 1.e-15)

n=3

for ((i=0; i<=n; i++)); do
    varname="array_$i"
    eval "vals=(\"\${${varname}[@]}\")"

    mkdir -p "./tmp/AMAM_GLOBAL/mesh_${vals[1]}_rennes"

    timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
    petscmpiexec -n ${vals[0]} ./bin/asynchronous-multisplitting-asynchronous-minimization-global-v1.0  -npb $(( ${vals[0]} / 2 )) \
    -m ${vals[1]} -n ${vals[1]} \
     -rtol ${vals[2]}  \
     -s ${vals[3]} \
     -min_convergence_count ${vals[4]} \
    -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_max_it ${vals[5]} -inner1_ksp_rtol ${vals[6]}  -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED   \
    -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_max_it ${vals[5]} -inner2_ksp_rtol ${vals[6]}  -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED   \
    -outer1_ksp_type lsqr  -outer1_ksp_convergence_test default -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_max_it ${vals[7]} -outer1_ksp_rtol ${vals[8]}  -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED       \
    -outer2_ksp_type lsqr  -outer2_ksp_convergence_test default -outer2_ksp_lsqr_exact_mat_norm -outer2_ksp_atol 1e-100 -outer2_ksp_max_it ${vals[7]} -outer2_ksp_rtol ${vals[8]}  -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED       \
    -options_view -options_left -log_view   > ./tmp/AMAM_GLOBAL/mesh_${vals[1]}_rennes/mesh_${vals[1]}_${vals[0]}procs_${i}.jl 2>&1 

done






# ==================================================================================================
# =========================# XXX Synchronous Multisplitting & Synchronous LOCAL minimization============
# ==================================================================================================
# -m 512 -n 512  -s 10 -rtol 7.e-7  



# array_i=(nprocs mesh_size rtol base_size inner_max_it inner_rtol outer_max_it outer_rtol )

# array_0=(16 32 1.e-10  10  20 1.e-20 70 1.e-20)

# array_1=(16 1024 1.e-10  10  20 1.e-20 70 1.e-20)
# array_2=(16 2048 1.e-10  10  20 1.e-20 70 1.e-20)
# array_3=(16 4096 1.e-10  10  20 1.e-20 70 1.e-20)
# array_4=(16 1024 1.e-10  10  20 1.e-20 70 1.e-20)
# array_5=(16 2048 1.e-10  10  20 1.e-20 70 1.e-20)
# array_6=(16 4096 1.e-10  10  20 1.e-20 70 1.e-20)
# array_7=(16 1024 1.e-10  10  30 1.e-20 70 1.e-20)
# array_8=(16 2048 1.e-10  10  30 1.e-20 70 1.e-20)
# array_9=(16 4096 1.e-10  10  30 1.e-20 70 1.e-20)


# array_10=(32 1024 1.e-10  10  20 1.e-20 70 1.e-20)
# array_11=(32 2048 1.e-10  10  20 1.e-20 70 1.e-20)
# array_12=(32 4096 1.e-10  10  20 1.e-20 70 1.e-20)
# array_13=(32 1024 1.e-10  10  20 1.e-20 70 1.e-20)
# array_14=(32 2048 1.e-10  10  20 1.e-20 70 1.e-20)
# array_15=(32 4096 1.e-10  10  20 1.e-20 70 1.e-20)
# array_16=(32 1024 1.e-10  10  20 1.e-20 70 1.e-20)
# array_17=(32 2048 1.e-10  10  20 1.e-20 70 1.e-20)
# array_18=(32 4096 1.e-10  10  20 1.e-20 70 1.e-20)

# n=18


# for ((i=0; i<=n; i++)); do
#     varname="array_$i"
#     eval "vals=(\"\${${varname}[@]}\")"

#     mkdir -p "./tmp/SMSM_LOCAL/mesh_${vals[1]}_grenoble"

#     timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
#     petscmpiexec -n ${vals[0]} ./bin/synchronous-multisplitting-synchronous-minimization-local-v1.0  -npb $(( ${vals[0]} / 2 )) \
#     -m ${vals[1]} -n ${vals[1]} \
#      -rtol ${vals[2]}  \
#      -s ${vals[3]} \
#     -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_max_it ${vals[4]} -inner1_ksp_rtol ${vals[5]}  -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED   \
#     -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_max_it ${vals[4]} -inner2_ksp_rtol ${vals[5]}  -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED   \
#     -outer1_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_max_it ${vals[6]} -outer1_ksp_rtol ${vals[7]}  -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED       \
#     -outer2_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer2_ksp_atol 1e-100 -outer2_ksp_max_it ${vals[6]} -outer2_ksp_rtol ${vals[7]}  -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED       \
#     -options_view -options_left -log_view   > ./tmp/SMSM_LOCAL/mesh_${vals[1]}_grenoble/mesh_${vals[1]}_${vals[0]}procs_${i}.jl 2>&1 

# done







# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-synchronous-minimization-local-v1.0  -npb 1 \
# -m 512 -n 512  -s 4 -rtol 1e-6  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-6 -inner1_ksp_max_it 30 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED  \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-6 -inner2_ksp_max_it 30 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED   \
# -outer1_ksp_type lsqr -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-12 -outer1_ksp_max_it 1000 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED     \
# -outer2_ksp_type lsqr -outer2_ksp_lsqr_exact_mat_norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-12 -outer2_ksp_max_it 1000 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED   \
# -options_view -options_left -log_view  > ./tmp/SMSM_LOCAL/tmp_3_1.yml 2>&1 



# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-synchronous-minimization-local-v1.0  -npb 1 \
# -m 512 -n 512  -s 10 -rtol 7.e-7  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 20 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED  -inner1_ksp_monitor_true_residual ascii:./tmp/SMSM_LOCAL/saved_tmp/inner1_ksp.yml \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 20 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED  -inner2_ksp_monitor_true_residual ascii:./tmp/SMSM_LOCAL/saved_tmp/inner2_ksp.yml \
# -outer1_ksp_type lsqr -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-20 -outer1_ksp_max_it 30 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED    -outer1_ksp_monitor_true_residual ascii:./tmp/SMSM_LOCAL/saved_tmp/outer1_ksp.yml -outer1_ksp_lsqr_monitor ascii:./tmp/SMSM_LOCAL/saved_tmp/outer1_lsqr.yml  \
# -outer2_ksp_type lsqr -outer2_ksp_lsqr_exact_mat_norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-20 -outer2_ksp_max_it 30 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED     -outer2_ksp_monitor_true_residual ascii:./tmp/SMSM_LOCAL/saved_tmp/outer2_ksp.yml -outer2_ksp_lsqr_monitor ascii:./tmp/SMSM_LOCAL/saved_tmp/outer2_lsqr.yml  \
# -options_view -options_left -log_view  > ./tmp/SMSM_LOCAL/saved_tmp/output.yml 2>&1 


# ==================================================================================================
# ==================# # XXX Asynchronous Multisplitting & Asynchronous LOCAL minimization===============
# ==================================================================================================


# array_i=(nprocs mesh_size rtol base_size min_conv_count inner_max_it inner_rtol outer_max_it outer_rtol )


# array_0=(16 32 1.e-10  10  3 20 1.e-20 70 1.e-20)

# array_1=(16 1024 1.e-10  10  3 20 1.e-20 70 1.e-20)
# array_2=(16 2048 1.e-10  10  3 20 1.e-20 70 1.e-20)
# array_3=(16 4096 1.e-10  10  3 20 1.e-20 70 1.e-20)
# array_4=(16 1024 1.e-10  10  3 20 1.e-20 70 1.e-20)
# array_5=(16 2048 1.e-10  10  3 20 1.e-20 70 1.e-20)
# array_6=(16 4096 1.e-10  10  3 20 1.e-20 70 1.e-20)
# array_7=(16 1024 1.e-10  10  3 30 1.e-20 70 1.e-20)
# array_8=(16 2048 1.e-10  10  3 30 1.e-20 70 1.e-20)
# array_9=(16 4096 1.e-10  10  3 30 1.e-20 70 1.e-20)


# array_10=(32 1024 1.e-10  10  3 20 1.e-20 70 1.e-20)
# array_11=(32 2048 1.e-10  10  3 20 1.e-20 70 1.e-20)
# array_12=(32 4096 1.e-10  10  3 20 1.e-20 70 1.e-20)
# array_13=(32 1024 1.e-10  10  3 20 1.e-20 70 1.e-20)
# array_14=(32 2048 1.e-10  10  3 20 1.e-20 70 1.e-20)
# array_15=(32 4096 1.e-10  10  3 20 1.e-20 70 1.e-20)
# array_16=(32 1024 1.e-10  10  3 20 1.e-20 70 1.e-20)
# array_17=(32 2048 1.e-10  10  3 20 1.e-20 70 1.e-20)
# array_18=(32 4096 1.e-10  10  3 20 1.e-20 70 1.e-20)

# n=18

# for ((i=0; i<=n; i++)); do
#     varname="array_$i"
#     eval "vals=(\"\${${varname}[@]}\")"

#     mkdir -p "./tmp/AMAM_LOCAL/mesh_${vals[1]}_grenoble"

#     timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
#     petscmpiexec -n ${vals[0]} ./bin/asynchronous-multisplitting-asynchronous-minimization-local-v1.0  -npb $(( ${vals[0]} / 2 )) \
#     -m ${vals[1]} -n ${vals[1]} \
#      -rtol ${vals[2]}  \
#      -s ${vals[3]} \
#      -min_convergence_count ${vals[4]} \
#     -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_max_it ${vals[5]} -inner1_ksp_rtol ${vals[6]}  -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED   \
#     -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_max_it ${vals[5]} -inner2_ksp_rtol ${vals[6]}  -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED   \
#     -outer1_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_max_it ${vals[7]} -outer1_ksp_rtol ${vals[8]}  -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED       \
#     -outer2_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer2_ksp_atol 1e-100 -outer2_ksp_max_it ${vals[7]} -outer2_ksp_rtol ${vals[8]}  -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED       \
#     -options_view -options_left -log_view   > ./tmp/AMAM_LOCAL/mesh_${vals[1]}_grenoble/mesh_${vals[1]}_${vals[0]}procs_${i}.jl 2>&1 

# done




# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/asynchronous-multisplitting-asynchronous-minimization-local-v1.0  -npb 1 \
# -m 512 -n 512  -s 4 -rtol 1e-6  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-6 -inner1_ksp_max_it 30 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED  \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-6 -inner2_ksp_max_it 30 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED   \
# -outer1_ksp_type lsqr -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-12 -outer1_ksp_max_it 1000 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED     \
# -outer2_ksp_type lsqr -outer2_ksp_lsqr_exact_mat_norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-12 -outer2_ksp_max_it 1000 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED   \
# -options_view -options_left -log_view  > ./tmp/AMAM_LOCAL/tmp_3_1.yml 2>&1 



# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/asynchronous-multisplitting-asynchronous-minimization-local-v1.0  -npb 1 \
# -m 512 -n 512  -s 10 -rtol 7.e-7  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 20 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED  -inner1_ksp_monitor_true_residual ascii:./tmp/AMAM_LOCAL/saved_tmp/inner1_ksp.yml \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 20 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED  -inner2_ksp_monitor_true_residual ascii:./tmp/AMAM_LOCAL/saved_tmp/inner2_ksp.yml \
# -outer1_ksp_type lsqr -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-20 -outer1_ksp_max_it 30 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED    -outer1_ksp_monitor_true_residual ascii:./tmp/AMAM_LOCAL/saved_tmp/outer1_ksp.yml -outer1_ksp_lsqr_monitor ascii:./tmp/AMAM_LOCAL/saved_tmp/outer1_lsqr.yml  \
# -outer2_ksp_type lsqr -outer2_ksp_lsqr_exact_mat_norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-20 -outer2_ksp_max_it 30 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED     -outer2_ksp_monitor_true_residual ascii:./tmp/AMAM_LOCAL/saved_tmp/outer2_ksp.yml -outer2_ksp_lsqr_monitor ascii:./tmp/AMAM_LOCAL/saved_tmp/outer2_lsqr.yml  \
# -options_view -options_left -log_view  > ./tmp/AMAM_LOCAL/saved_tmp/output.yml 2>&1 




# ==================================================================================================
# ==================================================================================================
# ==================================================================================================






# ==================================================================================================
# =========================# XXX Synchronous Multisplitting & Synchronous SEMI LOCAL minimization ============
# ==================================================================================================



# # array_i=(nprocs mesh_size rtol base_size inner_max_it inner_rtol outer_max_it outer_rtol )
# array_0=(16 32 1.e-4  10  30 1.e-20 70 1.e-15)
# array_1=(16 1024 1.e-4  10  30 1.e-20 70 1.e-15)
# array_2=(16 2048 1.e-4  10  30 1.e-20 70 1.e-15)
# array_3=(16 4096 1.e-4  10  30 1.e-20 70 1.e-15)
# array_4=(16 8192 1.e-4  10  30 1.e-20 70 1.e-15)
# n=0

# for ((i=0; i<=n; i++)); do
#     varname="array_$i"
#     eval "vals=(\"\${${varname}[@]}\")"

#     mkdir -p "./tmp/SMSM_SEMI_LOCAL/mesh_${vals[1]}_grenoble"

#     timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
#     petscmpiexec -n ${vals[0]} ./bin/synchronous-multisplitting-synchronous-minimization-semi-local-v1.0  -npb $(( ${vals[0]} / 2 )) \
#     -m ${vals[1]} -n ${vals[1]} \
#      -rtol ${vals[2]}  \
#      -s ${vals[3]} \
#     -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_max_it ${vals[4]} -inner1_ksp_rtol ${vals[5]}  -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED   \
#     -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_max_it ${vals[4]} -inner2_ksp_rtol ${vals[5]}  -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED   \
#     -outer1_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_max_it ${vals[6]} -outer1_ksp_rtol ${vals[7]}  -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED       \
#     -outer2_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer2_ksp_atol 1e-100 -outer2_ksp_max_it ${vals[6]} -outer2_ksp_rtol ${vals[7]}  -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED       \
#     -options_view -options_left -log_view   > ./tmp/SMSM_SEMI_LOCAL/mesh_${vals[1]}_grenoble/mesh_${vals[1]}_${vals[0]}procs.jl 2>&1 

# done



# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 16 ./bin/synchronous-multisplitting-synchronous-minimization-semi-local-v1.0  -npb 8 \
# -m 2048 -n 2048  -s 10 -rtol 1.e-4  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 20 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED  \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 20 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED   \
# -outer1_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-20 -outer1_ksp_max_it 70 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED       \
# -outer2_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_ norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-20 -outer2_ksp_max_it 70 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED       \
# -options_view -options_left -log_view  > ./tmp/SMSM_SEMI_LOCAL/mesh_2048/mesh_2048_16procs_6.yml 2>&1 


# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 16 ./bin/synchronous-multisplitting-synchronous-minimization-semi-local-v1.0  -npb 8 \
# -m 2048 -n 2048  -s 20 -rtol 1.e-4  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 20 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED  -inner1_ksp_monitor_true_residual ascii:./tmp/SMSM_SEMI_LOCAL/mesh_2048/perfs/inner1_ksp.yml \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 20 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED  -inner2_ksp_monitor_true_residual ascii:./tmp/SMSM_SEMI_LOCAL/mesh_2048/perfs/inner2_ksp.yml \
# -outer1_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-20 -outer1_ksp_max_it 70 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED     -outer1_ksp_monitor_true_residual ascii:./tmp/SMSM_SEMI_LOCAL/mesh_2048/perfs/outer1_ksp.yml -outer1_ksp_lsqr_monitor ascii:./tmp/SMSM_SEMI_LOCAL/mesh_2048/perfs/outer1_lsqr.yml   \
# -outer2_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_ norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-20 -outer2_ksp_max_it 70 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED     -outer2_ksp_monitor_true_residual ascii:./tmp/SMSM_SEMI_LOCAL/mesh_2048/perfs/outer2_ksp.yml  -outer2_ksp_lsqr_monitor ascii:./tmp/SMSM_SEMI_LOCAL/mesh_2048/perfs/outer2_lsqr.yml  \
# -options_view -options_left -log_view > ./tmp/SMSM_SEMI_LOCAL/mesh_2048/perfs/mesh_2048_16procs.yml 2>&1 



# ==================================================================================================
# =========================# XXX Asynchronous Multisplitting & Asynchronous SEMI LOCAL minimization ============
# ==================================================================================================




# # array_i=(nprocs mesh_size rtol base_size min_conv_count inner_max_it inner_rtol outer_max_it outer_rtol )
# array_0=(2 32 1.e-4  10  2 30 1.e-20 70 1.e-15)
# array_1=(2 1024 1.e-4  10  2 30 1.e-20 70 1.e-15)
# array_2=(2 2048 1.e-4  10  2 30 1.e-20 70 1.e-15)
# array_3=(2 4096 1.e-4  10  2 30 1.e-20 70 1.e-15)
# array_4=(2 8192 1.e-4  10  2 30 1.e-20 70 1.e-15)
# n=0

# for ((i=0; i<=n; i++)); do
#     varname="array_$i"
#     eval "vals=(\"\${${varname}[@]}\")"

#     mkdir -p "./tmp/AMAM_SEMI_LOCAL/mesh_${vals[1]}_grenoble"

#     timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
#     petscmpiexec -n ${vals[0]} ./bin/asynchronous-multisplitting-asynchronous-minimization-semi-local-v1.0  -npb $(( ${vals[0]} / 2 )) \
#     -m ${vals[1]} -n ${vals[1]} \
#      -rtol ${vals[2]}  \
#      -s ${vals[3]} \
#      -min_convergence_count ${vals[4]} \
#     -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_max_it ${vals[5]} -inner1_ksp_rtol ${vals[6]}  -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED   \
#     -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_max_it ${vals[5]} -inner2_ksp_rtol ${vals[6]}  -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED   \
#     -outer1_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_max_it ${vals[7]} -outer1_ksp_rtol ${vals[8]}  -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED       \
#     -outer2_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer2_ksp_atol 1e-100 -outer2_ksp_max_it ${vals[7]} -outer2_ksp_rtol ${vals[8]}  -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED       \
#     -options_view -options_left -log_view   > ./tmp/AMAM_SEMI_LOCAL/mesh_${vals[1]}_grenoble/mesh_${vals[1]}_${vals[0]}procs.jl 2>&1 

# done




# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 16 ./bin/asynchronous-multisplitting-saynchronous-minimization-semi-local-v1.0  -npb 8 \
# -m 2048 -n 2048  -s 10 -rtol 1.e-4  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 20 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED  \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 20 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED   \
# -outer1_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-20 -outer1_ksp_max_it 70 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED       \
# -outer2_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_ norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-20 -outer2_ksp_max_it 70 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED       \
# -options_view -options_left -log_view  > ./tmp/AMAM_SEMI_LOCAL/mesh_2048/mesh_2048_16procs_6.yml 2>&1 


# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 16 ./bin/asynchronous-multisplitting-asynchronous-minimization-semi-local-v1.0  -npb 8 \
# -m 2048 -n 2048  -s 20 -rtol 1.e-4  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 20 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED  -inner1_ksp_monitor_true_residual ascii:./tmp/AMAM_SEMI_LOCAL/mesh_2048/perfs/inner1_ksp.yml \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 20 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED  -inner2_ksp_monitor_true_residual ascii:./tmp/AMAM_SEMI_LOCAL/mesh_2048/perfs/inner2_ksp.yml \
# -outer1_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-20 -outer1_ksp_max_it 70 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED     -outer1_ksp_monitor_true_residual ascii:./tmp/AMAM_SEMI_LOCAL/mesh_2048/perfs/outer1_ksp.yml -outer1_ksp_lsqr_monitor ascii:./tmp/AMAM_SEMI_LOCAL/mesh_2048/perfs/outer1_lsqr.yml   \
# -outer2_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_ norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-20 -outer2_ksp_max_it 70 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED     -outer2_ksp_monitor_true_residual ascii:./tmp/AMAM_SEMI_LOCAL/mesh_2048/perfs/outer2_ksp.yml  -outer2_ksp_lsqr_monitor ascii:./tmp/AMAM_SEMI_LOCAL/mesh_2048/perfs/outer2_lsqr.yml  \
# -options_view -options_left -log_view > ./tmp/AMAM_SEMI_LOCAL/mesh_2048/perfs/mesh_2048_16procs.yml 2>&1 



# -options_view -options_left -log_view :output_G5k.xml:ascii_xml  > ./tmp/SMSM_GLOBAL/mesh_2048_rennes/mesh_2048_16procs.jl 2>&1 


# ==================================================================================================
# ==================================================================================================
# ==================================================================================================

set +x  # Disable command tracing

