#!/bin/bash

# Set the duration for the timeout
TIMEOUT_DURATION="600"

# Additionnal grace period
ADDITIONAL_GRACE_PERIOD="5s"

# mkdir -p ./tmp/logs
# mkdir -p ./tmp/logs_SM
# mkdir -p ./tmp/logs_AM
# mkdir -p ./tmp/logs_SMSM_LOCAL
# mkdir -p ./tmp/logs_AMAM_LOCAL
# mkdir -p ./tmp/logs_SMSM_GLOBAL
# mkdir -p ./tmp/logs_AMAM_GLOBAL
# rm -drf ./tmp/logs_SM/*
# rm -drf ./tmp/logs_AM/*
# rm -drf ./tmp/logs_SMSM_LOCAL/*
# rm -drf ./tmp/logs_AMAM_LOCAL/*
# rm -drf ./tmp/logs_SMSM_GLOBAL/*
# rm -drf ./tmp/logs_AMAM_GLOBAL/*

set -x  # Enable command tracing



# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/exp-v1.0 




# ==================================================================================================
# ============================# GMRES SOLUTION =====================================
# ==================================================================================================


# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 4 ./bin/gmres_solution-v1.0 \
# -m 32 -n 32  \
# -ksp_type gmres -ksp_rtol 1e-4 -ksp_atol 1e-100 -ksp_max_it 1000000000 -pc_type  none \
# -ksp_norm_type UNPRECONDITIONED -ksp_converged_use_initial_residual_norm \
# -ksp_gmres_restart 30 \
# -ksp_converged_reason -ksp_view_final_residual  -malloc_debug \


# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 4 ./bin/gmres_solution-v1.0 \
# -m 4 -n 4  \
# -ksp_type gmres -ksp_rtol 1e-4 -ksp_atol 1e-100 -ksp_max_it 1000000000 -pc_type  none \
# -ksp_norm_type UNPRECONDITIONED -ksp_converged_use_initial_residual_norm \
# -ksp_gmres_restart 30 \
# -ksp_converged_reason -ksp_view_final_residual  -ksp_error_if_not_converged -ksp_view_pre  \
# -options_view -options_left -log_view > ./tmp/GMRES/output_2.jl 2>&1




# ==================================================================================================
# ============================# Synchronous Multisplitting=====================================
# ==================================================================================================

# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 4 ./bin/synchronous-multisplitting-v1.0  -npb 2  \
# -m 32 -n 32  -rtol 1.e-2  \
# -inner1_ksp_type gmres -inner1_ksp_atol 1e-100  -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 20 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED -inner1_ksp_converged_use_initial_residual_norm        \
# -inner2_ksp_type gmres -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 20 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED -inner2_ksp_converged_use_initial_residual_norm      \
# -malloc_debug \
# -options_view -options_left  -log_view -log_trace output  > ./tmp/SM/mesh_512/mesh_512_2procs_2.jl 2>&1


# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-v1.0  -npb 1  \
# -m 512 -n 512  -rtol 1.e-5  \
# -inner1_ksp_type gmres -inner1_ksp_atol 1e-100  -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 50 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED -inner1_ksp_converged_use_initial_residual_norm       \
# -inner2_ksp_type gmres -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 50 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED -inner2_ksp_converged_use_initial_residual_norm     \
# -options_view -options_left  -log_view  > ./tmp/SM/mesh_512/mesh_512_2procs.jl 2>&1


# timeout -k $ADDITIONAL_ GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-v1.0  -npb 1 \
# -m 512 -n 512  -rtol 1e-8  \
# -inner1_ksp_type gmres -inner1_ksp_atol 1e-100  -inner1_ksp_rtol 1e-3 -inner1_ksp_max_it 50 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED -inner1_ksp_converged_use_initial_residual_norm     \
# -inner2_ksp_type gmres -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-3 -inner2_ksp_max_it 50 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED -inner2_ksp_converged_use_initial_residual_norm    \
# -options_view -options_left  -log_view  > ./tmp/SM/log_4_0.jl 2>&1


# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-v1.0  -npb 1 \
# -m 512 -n 512  -rtol 1e-6  \
# -inner1_ksp_type gmres -inner1_ksp_atol 1e-100  -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 50 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED -inner1_ksp_converged_use_initial_residual_norm     \
# -inner2_ksp_type gmres -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 50 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED -inner2_ksp_converged_use_initial_residual_norm    \
# -options_view -options_left  -log_view  > ./tmp/SM/log_3_0_temp2.jl 2>&1

# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-v1.0  -npb 1 \
# -m 512 -n 512  -rtol 1e-6  \
# -inner1_ksp_type gmres -inner1_ksp_atol 1e-100  -inner1_ksp_rtol 1e-6 -inner1_ksp_max_it 50 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED -inner1_ksp_converged_use_initial_residual_norm     \
# -inner2_ksp_type gmres -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-6 -inner2_ksp_max_it 50 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED -inner2_ksp_converged_use_initial_residual_norm    \
# -options_view -options_left  -log_view  > ./tmp/SM/log_3_0_temp3.jl 2>&1






# ==================================================================================================
# ============================# # Asynchronous Multisplitting=======================================
# ==================================================================================================

# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/asynchronous-multisplitting-v1.0  -npb 1  \
# -m 32 -n 32  -rtol 1.e-3  \
# -min_convergence_count 5 \
# -inner1_ksp_type gmres -inner1_ksp_atol 1e-100  -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 20 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED -inner1_ksp_converged_use_initial_residual_norm        \
# -inner2_ksp_type gmres -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 20 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED -inner2_ksp_converged_use_initial_residual_norm        \
# -options_view -options_left  -log_view  > ./tmp/AM/mesh_1024/mesh_1024_2procs.jl 2>&1






# ==================================================================================================
# =========================# Synchronous Multisplitting & Synchronous LOCAL minimization============
# ==================================================================================================
# -m 512 -n 512  -s 10 -rtol 7.e-7  ou 4.e-7


# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-synchronous-minimization-local-v1.0  -npb 1 \
# -m 32 -n 32  -s 4 -rtol 7.e-7  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-6 -inner1_ksp_max_it 20 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED  \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-6 -inner2_ksp_max_it 20 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED   \
# -outer1_ksp_type lsqr -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-15 -outer1_ksp_max_it 50 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED     \
# -outer2_ksp_type lsqr -outer2_ksp_lsqr_exact_mat_norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-15 -outer2_ksp_max_it 50 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED   \
# -malloc_debug \
# -options_view -options_left -log_view  > ./tmp/SMSM_LOCAL/mesh_512/mesh_512_test.yml 2>&1 



# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-synchronous-minimization-local-v1.0  -npb 1 \
# -m 512 -n 512  -s 10 -rtol 7.e-7  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 20 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED  -inner1_ksp_monitor_true_residual ascii:./tmp/SMSM_LOCAL/saved_tmp/inner1_ksp.yml \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 20 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED  -inner2_ksp_monitor_true_residual ascii:./tmp/SMSM_LOCAL/saved_tmp/inner2_ksp.yml \
# -outer1_ksp_type lsqr -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-20 -outer1_ksp_max_it 30 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED    -outer1_ksp_monitor_true_residual ascii:./tmp/SMSM_LOCAL/saved_tmp/outer1_ksp.yml -outer1_ksp_lsqr_monitor ascii:./tmp/SMSM_LOCAL/saved_tmp/outer1_lsqr.yml  \
# -outer2_ksp_type lsqr -outer2_ksp_lsqr_exact_mat_norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-20 -outer2_ksp_max_it 30 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED     -outer2_ksp_monitor_true_residual ascii:./tmp/SMSM_LOCAL/saved_tmp/outer2_ksp.yml -outer2_ksp_lsqr_monitor ascii:./tmp/SMSM_LOCAL/saved_tmp/outer2_lsqr.yml  \
# -options_view -options_left -log_view  > ./tmp/SMSM_LOCAL/saved_tmp/output.yml 2>&1 


# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-synchronous-minimization-local-v1.0  -npb 1 \
# -m 512 -n 512  -s 2 -rtol 7.e-7  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 20 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED   \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 20 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED   \
# -outer1_ksp_type lsqr -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-50 -outer1_ksp_max_it 50 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED       \
# -outer2_ksp_type lsqr -outer2_ksp_lsqr_exact_mat_norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-50 -outer2_ksp_max_it 50 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED     \
# -options_view -options_left -log_view  > ./tmp/SMSM_LOCAL/saved_tmp/output.yml 2>&1 


# ==================================================================================================
# ==================# # Asynchronous Multisplitting & Asynchronous LOCAL minimization===============
# ==================================================================================================

# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 4 ./bin/asynchronous-multisplitting-asynchronous-minimization-local-v1.0  -npb 2 \
# -m 2048 -n 2048  -s 10 -rtol 1.e-1  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 20 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED  \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 20 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED   \
# -outer1_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-20 -outer1_ksp_max_it 70 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED       \
# -outer2_ksp_type lsqr  -outer2_ksp_lsqr_exact_mat_norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-20 -outer2_ksp_max_it 70 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED       \
# -options_view -options_left -log_view -malloc_debug > ./tmp/AMAM_LOCAL/mesh_2048/mesh_2048.yml 2>&1 
# -malloc_debug \




# ==================================================================================================
# ===========# # Synchronous Multisplitting & Synchronous GLOBAL minimization=======================
# ==================================================================================================


# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-synchronous-minimization-global-v1.0  -npb 1 \
# -m 32 -n 32  -s 4 -rtol 1e-3  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-3 -inner1_ksp_max_it 20 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED   \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-3 -inner2_ksp_max_it 20 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED   \
# -outer1_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-20 -outer1_ksp_max_it 70 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED       \
# -outer2_ksp_type lsqr  -outer2_ksp_lsqr_exact_mat_norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-20 -outer2_ksp_max_it 70 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED       \
# -malloc_debug 


# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 4 ./bin/synchronous-multisplitting-synchronous-minimization-global-v1.0  -npb 2 \
# -m 32 -n 32  -s 4 -rtol 1e-4  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-3 -inner1_ksp_max_it 20 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED   \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-3 -inner2_ksp_max_it 20 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED   \
# -outer1_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-20 -outer1_ksp_max_it 70 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED       \
# -outer2_ksp_type lsqr  -outer2_ksp_lsqr_exact_mat_norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-20 -outer2_ksp_max_it 70 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED       \
# -options_view -options_left -log_view > ./tmp/SMSM_GLOBAL/exp/output.yml 2>&1




# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-synchronous-minimization-global-v1.0  -npb 1 \
# -m 512 -n 512  -s 10 -rtol 1e-6  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-15 -inner1_ksp_max_it 7 -inner1_pc_type none -inner1_ksp_norm_type unpreconditioned  -inner1_ksp_monitor_true_residual ascii:./tmp/exp/inner1_ksp.yml \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-15 -inner2_ksp_max_it 7 -inner2_pc_type none -inner2_ksp_norm_type unpreconditioned  -inner2_ksp_monitor_true_residual ascii:./tmp/exp/inner2_ksp.yml \
# -outer1_ksp_type lsqr -outer1_ksp_convergence_test default  -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-15 -outer1_ksp_max_it 15 -outer1_pc_type none -outer1_ksp_norm_type unpreconditioned    -outer1_ksp_converged_reason -outer1_ksp_monitor_true_residual ascii:./tmp/exp/outer1_ksp.yml -outer1_ksp_lsqr_monitor ascii:./tmp/exp/outer1_lsqr.yml   \
# -outer2_ksp_type lsqr  -outer2_ksp_convergence_test default -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-15 -outer2_ksp_max_it 15 -outer2_pc_type none -outer2_ksp_norm_type unpreconditioned  -outer2_ksp_converged_reason -outer2_ksp_monitor_true_residual ascii:./tmp/exp/outer2_ksp.yml  -outer2_ksp_lsqr_monitor ascii:./tmp/exp/outer2_lsqr.yml  \
# -options_view -options_left -log_view  > ./tmp/exp/output.yml 2>&1 



# ==================================================================================================
# ========= # Asynchronous Multisplitting & Asynchronous GLOBAL minimization========================
# ==================================================================================================


timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
petscmpiexec -n 4 ./bin/asynchronous-multisplitting-asynchronous-minimization-global-v1.0  -npb 2 \
-m 2048 -n 2048  -s 2 -rtol 9.e-1 -min_convergence_count 1 \
-inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1.e-100 -inner1_ksp_rtol 1.e-3 -inner1_ksp_max_it 20 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED   \
-inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1.e-100 -inner2_ksp_rtol 1.e-3 -inner2_ksp_max_it 20 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED   \
-outer1_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1.e-15 -outer1_ksp_max_it 70 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED       \
-outer2_ksp_type lsqr  -outer2_ksp_lsqr_exact_mat_norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1.e-15 -outer2_ksp_max_it 70 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED       \
-malloc_debug -log_view > ./tmp/AMAM_GLOBAL/mesh_2048/mesh_2048.yml 2>&1 
# -options_view -options_left -log_view -malloc_debug> ./tmp/AMAM_GLOBAL/mesh_2048/mesh_2048.yml 2>&1 
# -malloc_debug






# ==================================================================================================
# =========================# Synchronous Multisplitting & Synchronous SEMI LOCAL minimization ============
# ==================================================================================================
# -m 512 -n 512  -s 5 -rtol 9.e-6 

# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-synchronous-minimization-semi-local-v1.0  -npb 1 \
# -m 32 -n 32  -s 4 -rtol 1.e-4  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 20 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED  \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 20 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED   \
# -outer1_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-20 -outer1_ksp_max_it 70 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED       \
# -outer2_ksp_type lsqr  -outer2_ksp_lsqr_exact_mat_norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-20 -outer2_ksp_max_it 70 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED       \
# -malloc_debug \
# -options_view -options_left -log_view

# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-synchronous-minimization-semi-local-v1.0  -npb 1 \
# -m 512 -n 512  -s 10 -rtol 1.e-4  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 20 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED  \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 20 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED   \
# -outer1_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-20 -outer1_ksp_max_it 70 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED       \
# -outer2_ksp_type lsqr  -outer2_ksp_lsqr_exact_mat_norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-20 -outer2_ksp_max_it 70 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED       \
# -options_view -options_left -log_view > ./tmp/SMSM_SEMI_LOCAL/mesh_512/mesh_512.yml 2>&1 


# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-synchronous-minimization-semi-local-v1.0  -npb 1 \
# -m 512 -n 512  -s 5 -rtol 9.e-6  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 20 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED  -inner1_ksp_monitor_true_residual ascii:./tmp/SMSM_SEMI_LOCAL/saved_tmp/inner1_ksp.yml \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 20 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED  -inner2_ksp_monitor_true_residual ascii:./tmp/SMSM_SEMI_LOCAL/saved_tmp/inner2_ksp.yml \
# -outer1_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-50 -outer1_ksp_max_it 100 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED    -outer1_ksp_converged_reason -outer1_ksp_monitor_true_residual ascii:./tmp/SMSM_SEMI_LOCAL/saved_tmp/outer1_ksp.yml -outer1_ksp_lsqr_monitor ascii:./tmp/SMSM_SEMI_LOCAL/saved_tmp/outer1_lsqr.yml   \
# -outer2_ksp_type lsqr  -outer2_ksp_lsqr_exact_mat_norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-50 -outer2_ksp_max_it 100 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED    -outer2_ksp_converged_reason -outer2_ksp_monitor_true_residual ascii:./tmp/SMSM_SEMI_LOCAL/saved_tmp/outer2_ksp.yml  -outer2_ksp_lsqr_monitor ascii:./tmp/SMSM_SEMI_LOCAL/saved_tmp/outer2_lsqr.yml  \
# -options_view -options_left -log_view > ./tmp/SMSM_SEMI_LOCAL/saved_tmp/output.yml 2>&1 



# ==================================================================================================
# =========================# Asynchronous Multisplitting & Asynchronous SEMI LOCAL minimization ============
# ==================================================================================================
# -m 512 -n 512  -s 5 -rtol 9.e-6 

# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 4 ./bin/asynchronous-multisplitting-asynchronous-minimization-semi-local-v1.0  -npb 2 \
# -m 32 -n 32  -s 4 -rtol 1.e-3  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 20 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED  \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 20 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED   \
# -outer1_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-20 -outer1_ksp_max_it 70 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED       \
# -outer2_ksp_type lsqr  -outer2_ksp_lsqr_exact_mat_norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-20 -outer2_ksp_max_it 70 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED       \
# -options_view -options_left -log_view

# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-synchronous-minimization-semi-local-v1.0  -npb 1 \
# -m 512 -n 512  -s 10 -rtol 1.e-4  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 20 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED  \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 20 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED   \
# -outer1_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-20 -outer1_ksp_max_it 70 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED       \
# -outer2_ksp_type lsqr  -outer2_ksp_lsqr_exact_mat_ norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-20 -outer2_ksp_max_it 70 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED       \
# -options_view -options_left -log_view > ./tmp/SMSM_SEMI_LOCAL/mesh_512/mesh_512.yml 2>&1 


# timeout -k $ADDITIONAL_GRACE_PERIOD $TIMEOUT_DURATION bash \
# petscmpiexec -n 2 ./bin/synchronous-multisplitting-synchronous-minimization-semi-local-v1.0  -npb 1 \
# -m 512 -n 512  -s 5 -rtol 9.e-6  \
# -inner1_ksp_type gmres -inner1_ksp_gmres_preallocate -inner1_ksp_gmres_restart 30 -inner1_ksp_atol 1e-100 -inner1_ksp_rtol 1e-10 -inner1_ksp_max_it 20 -inner1_pc_type none -inner1_ksp_norm_type UNPRECONDITIONED  -inner1_ksp_monitor_true_residual ascii:./tmp/SMSM_SEMI_LOCAL/saved_tmp/inner1_ksp.yml \
# -inner2_ksp_type gmres -inner2_ksp_gmres_preallocate -inner2_ksp_gmres_restart 30 -inner2_ksp_atol 1e-100 -inner2_ksp_rtol 1e-10 -inner2_ksp_max_it 20 -inner2_pc_type none -inner2_ksp_norm_type UNPRECONDITIONED  -inner2_ksp_monitor_true_residual ascii:./tmp/SMSM_SEMI_LOCAL/saved_tmp/inner2_ksp.yml \
# -outer1_ksp_type lsqr  -outer1_ksp_lsqr_exact_mat_norm -outer1_ksp_atol 1e-100 -outer1_ksp_rtol 1e-50 -outer1_ksp_max_it 100 -outer1_pc_type none -outer1_ksp_norm_type UNPRECONDITIONED    -outer1_ksp_converged_reason -outer1_ksp_monitor_true_residual ascii:./tmp/SMSM_SEMI_LOCAL/saved_tmp/outer1_ksp.yml -outer1_ksp_lsqr_monitor ascii:./tmp/SMSM_SEMI_LOCAL/saved_tmp/outer1_lsqr.yml   \
# -outer2_ksp_type lsqr  -outer2_ksp_lsqr_exact_mat_ norm -outer2_ksp_atol 1e-100 -outer2_ksp_rtol 1e-50 -outer2_ksp_max_it 100 -outer2_pc_type none -outer2_ksp_norm_type UNPRECONDITIONED    -outer2_ksp_converged_reason -outer2_ksp_monitor_true_residual ascii:./tmp/SMSM_SEMI_LOCAL/saved_tmp/outer2_ksp.yml  -outer2_ksp_lsqr_monitor ascii:./tmp/SMSM_SEMI_LOCAL/saved_tmp/outer2_lsqr.yml  \
# -options_view -options_left -log_view > ./tmp/SMSM_SEMI_LOCAL/saved_tmp/output.yml 2>&1 



# ==================================================================================================
# ==================================================================================================
# ==================================================================================================
set +x  # Disable command tracing




# # replace the root on br0
# sudo tc qdisc replace dev br0 root handle 1: htb default 20
# sudo tc class  add dev br0 parent 1: classid 1:10 htb rate 50mbit ceil 50mbit
# sudo tc qdisc  add dev br0 parent 1:10 handle 10: tbf rate 50mbit burst 25kb latency 100ms

# # (optional filters to steer by destination)
# # sudo tc filter add dev br0 protocol ip parent 1: prio 1 u32 match ip dst 172.16.31.101/32 flowid 1:10

# tc -s qdisc show dev br0